In [1]:
import numpy as np

In [3]:
p=np.array((1,2,3,4))
print(p)
print(type(p))

[1 2 3 4]
<class 'numpy.ndarray'>


In [11]:
p=np.arange(11)
print(p)
k=np.arange(1,50,2)
print(k)
#float use the int variable
z=np.zeros(10,int)
print(z)
o=np.ones(10)
print(o)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
[0 0 0 0 0 0 0 0 0 0]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [14]:
#matrix
mat=np.ones((3,3))
print(mat)
mat1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
#identity matrix
mat2=np.eye(3,dtype=int)
print(mat2)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [34]:
#array op
mat4=np.arange(1,8)
print(mat4)
print(mat4[1:5])
print(mat4[:5])
print(mat4[4:])
print(mat4[-4:-1])
print(mat4[4])
mat4[2]=10
print(mat4)
b=np.copy(mat4)
print(b)

[1 2 3 4 5 6 7]
[2 3 4 5]
[1 2 3 4 5]
[5 6 7]
[4 5 6]
5
[ 1  2 10  4  5  6  7]
[ 1  2 10  4  5  6  7]


In [42]:
a=np.array((1,2,3,4,5))
b=np.array((4,5,6,7,8))
print("first:",a,"second:",b)
new=np.concatenate((a,b))
print(new)
m1=np.array([[1,2,3],[4,5,6]])
m2=np.array([[1,8],[7,9]])
newarr=np.concatenate((m1,m2),axis=1)
print(newarr)

first: [1 2 3 4 5] second: [4 5 6 7 8]
[1 2 3 4 5 4 5 6 7 8]
[[1 2 3 1 8]
 [4 5 6 7 9]]


In [53]:
ar=np.array((2,3,5,8,9,7,2))
x=np.where(ar==3)
print(x)
print(x[0])
if((x[0].size)>0):
    print("number of times found:")
    print(*x[0]+1)
else:
    print("Number is not found")

(array([1]),)
[1]
number of times found:
2
